/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AbaTherapyRouteImport } from './routes/aba-therapy'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AutismTherapyRouteImport } from './routes/autism-therapy'
import { Route as BehavioralTherapyRouteImport } from './routes/behavioral-therapy'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as DanceTherapyRouteImport } from './routes/dance-therapy'
import { Route as DiagnosticsRouteImport } from './routes/diagnostics'
import { Route as DoctorsRouteImport } from './routes/doctors'
import { Route as GrowthDevelopmentRouteImport } from './routes/growth-development'
import { Route as OccupationalTherapyRouteImport } from './routes/occupational-therapy'
import { Route as PsychologicalCounselingRouteImport } from './routes/psychological-counseling'
import { Route as ResourcesRouteImport } from './routes/resources'
import { Route as SpecialEducationRouteImport } from './routes/special-education'

import { Route as SpeechTherapyRouteImport } from './routes/speech-therapy'
import { Route as StoriesRouteImport } from './routes/stories'
import { Route as VaccinationRouteImport } from './routes/vaccination'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AbaTherapyRoute = AbaTherapyRouteImport.update({
  id: '/aba-therapy',
  path: '/aba-therapy',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AutismTherapyRoute = AutismTherapyRouteImport.update({
  id: '/autism-therapy',
  path: '/autism-therapy',
  getParentRoute: () => rootRouteImport,
} as any)
const BehavioralTherapyRoute = BehavioralTherapyRouteImport.update({
  id: '/behavioral-therapy',
  path: '/behavioral-therapy',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const DanceTherapyRoute = DanceTherapyRouteImport.update({
  id: '/dance-therapy',
  path: '/dance-therapy',
  getParentRoute: () => rootRouteImport,
} as any)
const DiagnosticsRoute = DiagnosticsRouteImport.update({
  id: '/diagnostics',
  path: '/diagnostics',
  getParentRoute: () => rootRouteImport,
} as any)
const DoctorsRoute = DoctorsRouteImport.update({
  id: '/doctors',
  path: '/doctors',
  getParentRoute: () => rootRouteImport,
} as any)
const GrowthDevelopmentRoute = GrowthDevelopmentRouteImport.update({
  id: '/growth-development',
  path: '/growth-development',
  getParentRoute: () => rootRouteImport,
} as any)
const OccupationalTherapyRoute = OccupationalTherapyRouteImport.update({
  id: '/occupational-therapy',
  path: '/occupational-therapy',
  getParentRoute: () => rootRouteImport,
} as any)
const PsychologicalCounselingRoute = PsychologicalCounselingRouteImport.update({
  id: '/psychological-counseling',
  path: '/psychological-counseling',
  getParentRoute: () => rootRouteImport,
} as any)
const ResourcesRoute = ResourcesRouteImport.update({
  id: '/resources',
  path: '/resources',
  getParentRoute: () => rootRouteImport,
} as any)
const SpecialEducationRoute = SpecialEducationRouteImport.update({
  id: '/special-education',
  path: '/special-education',
  getParentRoute: () => rootRouteImport,
} as any)
const SpeechTherapyRoute = SpeechTherapyRouteImport.update({
  id: '/speech-therapy',
  path: '/speech-therapy',
  getParentRoute: () => rootRouteImport,
} as any)
const StoriesRoute = StoriesRouteImport.update({
  id: '/stories',
  path: '/stories',
  getParentRoute: () => rootRouteImport,
} as any)
const VaccinationRoute = VaccinationRouteImport.update({
  id: '/vaccination',
  path: '/vaccination',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/aba-therapy': typeof AbaTherapyRoute
  '/about': typeof AboutRoute
  '/autism-therapy': typeof AutismTherapyRoute
  '/behavioral-therapy': typeof BehavioralTherapyRoute
  '/contact': typeof ContactRoute
  '/dance-therapy': typeof DanceTherapyRoute
  '/diagnostics': typeof DiagnosticsRoute
  '/doctors': typeof DoctorsRoute
  '/growth-development': typeof GrowthDevelopmentRoute
  '/occupational-therapy': typeof OccupationalTherapyRoute
  '/psychological-counseling': typeof PsychologicalCounselingRoute
  '/resources': typeof ResourcesRoute
  '/special-education': typeof SpecialEducationRoute
  '/speech-therapy': typeof SpeechTherapyRoute
  '/stories': typeof StoriesRoute
  '/vaccination': typeof VaccinationRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/aba-therapy': typeof AbaTherapyRoute
  '/about': typeof AboutRoute
  '/autism-therapy': typeof AutismTherapyRoute
  '/behavioral-therapy': typeof BehavioralTherapyRoute
  '/contact': typeof ContactRoute
  '/dance-therapy': typeof DanceTherapyRoute
  '/diagnostics': typeof DiagnosticsRoute
  '/doctors': typeof DoctorsRoute
  '/growth-development': typeof GrowthDevelopmentRoute
  '/occupational-therapy': typeof OccupationalTherapyRoute
  '/psychological-counseling': typeof PsychologicalCounselingRoute
  '/resources': typeof ResourcesRoute
  '/special-education': typeof SpecialEducationRoute
  '/speech-therapy': typeof SpeechTherapyRoute
  '/stories': typeof StoriesRoute
  '/vaccination': typeof VaccinationRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/aba-therapy': typeof AbaTherapyRoute
  '/about': typeof AboutRoute
  '/autism-therapy': typeof AutismTherapyRoute
  '/behavioral-therapy': typeof BehavioralTherapyRoute
  '/contact': typeof ContactRoute
  '/dance-therapy': typeof DanceTherapyRoute
  '/diagnostics': typeof DiagnosticsRoute
  '/doctors': typeof DoctorsRoute
  '/growth-development': typeof GrowthDevelopmentRoute
  '/occupational-therapy': typeof OccupationalTherapyRoute
  '/psychological-counseling': typeof PsychologicalCounselingRoute
  '/resources': typeof ResourcesRoute
  '/special-education': typeof SpecialEducationRoute
  '/speech-therapy': typeof SpeechTherapyRoute
  '/stories': typeof StoriesRoute
  '/vaccination': typeof VaccinationRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/aba-therapy'
    | '/about'
    | '/autism-therapy'
    | '/behavioral-therapy'
    | '/contact'
    | '/dance-therapy'
    | '/diagnostics'
    | '/doctors'
    | '/growth-development'
    | '/occupational-therapy'
    | '/psychological-counseling'
    | '/resources'
    | '/special-education'
    | '/speech-therapy'
    | '/stories'
    | '/vaccination'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/aba-therapy'
    | '/about'
    | '/autism-therapy'
    | '/behavioral-therapy'
    | '/contact'
    | '/dance-therapy'
    | '/diagnostics'
    | '/doctors'
    | '/growth-development'
    | '/occupational-therapy'
    | '/psychological-counseling'
    | '/resources'
    | '/special-education'
    | '/speech-therapy'
    | '/stories'
    | '/vaccination'
  id:
    | '__root__'
    | '/'
    | '/aba-therapy'
    | '/about'
    | '/autism-therapy'
    | '/behavioral-therapy'
    | '/contact'
    | '/dance-therapy'
    | '/diagnostics'
    | '/doctors'
    | '/growth-development'
    | '/occupational-therapy'
    | '/psychological-counseling'
    | '/resources'
    | '/special-education'
    | '/speech-therapy'
    | '/stories'
    | '/vaccination'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AbaTherapyRoute: typeof AbaTherapyRoute
  AboutRoute: typeof AboutRoute
  AutismTherapyRoute: typeof AutismTherapyRoute
  BehavioralTherapyRoute: typeof BehavioralTherapyRoute
  ContactRoute: typeof ContactRoute
  DanceTherapyRoute: typeof DanceTherapyRoute
  DiagnosticsRoute: typeof DiagnosticsRoute
  DoctorsRoute: typeof DoctorsRoute
  GrowthDevelopmentRoute: typeof GrowthDevelopmentRoute
  OccupationalTherapyRoute: typeof OccupationalTherapyRoute
  PsychologicalCounselingRoute: typeof PsychologicalCounselingRoute
  ResourcesRoute: typeof ResourcesRoute
  SpecialEducationRoute: typeof SpecialEducationRoute
  SpeechTherapyRoute: typeof SpeechTherapyRoute
  StoriesRoute: typeof StoriesRoute
  VaccinationRoute: typeof VaccinationRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/aba-therapy': {
      id: '/aba-therapy'
      path: '/aba-therapy'
      fullPath: '/aba-therapy'
      preLoaderRoute: typeof AbaTherapyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/autism-therapy': {
      id: '/autism-therapy'
      path: '/autism-therapy'
      fullPath: '/autism-therapy'
      preLoaderRoute: typeof AutismTherapyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/behavioral-therapy': {
      id: '/behavioral-therapy'
      path: '/behavioral-therapy'
      fullPath: '/behavioral-therapy'
      preLoaderRoute: typeof BehavioralTherapyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dance-therapy': {
      id: '/dance-therapy'
      path: '/dance-therapy'
      fullPath: '/dance-therapy'
      preLoaderRoute: typeof DanceTherapyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/diagnostics': {
      id: '/diagnostics'
      path: '/diagnostics'
      fullPath: '/diagnostics'
      preLoaderRoute: typeof DiagnosticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/doctors': {
      id: '/doctors'
      path: '/doctors'
      fullPath: '/doctors'
      preLoaderRoute: typeof DoctorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/growth-development': {
      id: '/growth-development'
      path: '/growth-development'
      fullPath: '/growth-development'
      preLoaderRoute: typeof GrowthDevelopmentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/occupational-therapy': {
      id: '/occupational-therapy'
      path: '/occupational-therapy'
      fullPath: '/occupational-therapy'
      preLoaderRoute: typeof OccupationalTherapyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/psychological-counseling': {
      id: '/psychological-counseling'
      path: '/psychological-counseling'
      fullPath: '/psychological-counseling'
      preLoaderRoute: typeof PsychologicalCounselingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resources': {
      id: '/resources'
      path: '/resources'
      fullPath: '/resources'
      preLoaderRoute: typeof ResourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/special-education': {
      id: '/special-education'
      path: '/special-education'
      fullPath: '/special-education'
      preLoaderRoute: typeof SpecialEducationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/speech-therapy': {
      id: '/speech-therapy'
      path: '/speech-therapy'
      fullPath: '/speech-therapy'
      preLoaderRoute: typeof SpeechTherapyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stories': {
      id: '/stories'
      path: '/stories'
      fullPath: '/stories'
      preLoaderRoute: typeof StoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vaccination': {
      id: '/vaccination'
      path: '/vaccination'
      fullPath: '/vaccination'
      preLoaderRoute: typeof VaccinationRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AbaTherapyRoute: AbaTherapyRoute,
  AboutRoute: AboutRoute,
  AutismTherapyRoute: AutismTherapyRoute,
  BehavioralTherapyRoute: BehavioralTherapyRoute,
  ContactRoute: ContactRoute,
  DanceTherapyRoute: DanceTherapyRoute,
  DiagnosticsRoute: DiagnosticsRoute,
  DoctorsRoute: DoctorsRoute,
  GrowthDevelopmentRoute: GrowthDevelopmentRoute,
  OccupationalTherapyRoute: OccupationalTherapyRoute,
  PsychologicalCounselingRoute: PsychologicalCounselingRoute,
  ResourcesRoute: ResourcesRoute,
  SpecialEducationRoute: SpecialEducationRoute,
  SpeechTherapyRoute: SpeechTherapyRoute,
  StoriesRoute: StoriesRoute,
  VaccinationRoute: VaccinationRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
