/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as DiagnosticsRouteImport } from './routes/diagnostics'
import { Route as DoctorsRouteImport } from './routes/doctors'
import { Route as GrowthDevelopmentRouteImport } from './routes/growth-development'
import { Route as ResourcesRouteImport } from './routes/resources'
import { Route as SpecialtiesRouteImport } from './routes/specialties'
import { Route as StoriesRouteImport } from './routes/stories'
import { Route as VaccinationRouteImport } from './routes/vaccination'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const DiagnosticsRoute = DiagnosticsRouteImport.update({
  id: '/diagnostics',
  path: '/diagnostics',
  getParentRoute: () => rootRouteImport,
} as any)
const DoctorsRoute = DoctorsRouteImport.update({
  id: '/doctors',
  path: '/doctors',
  getParentRoute: () => rootRouteImport,
} as any)
const GrowthDevelopmentRoute = GrowthDevelopmentRouteImport.update({
  id: '/growth-development',
  path: '/growth-development',
  getParentRoute: () => rootRouteImport,
} as any)
const ResourcesRoute = ResourcesRouteImport.update({
  id: '/resources',
  path: '/resources',
  getParentRoute: () => rootRouteImport,
} as any)
const SpecialtiesRoute = SpecialtiesRouteImport.update({
  id: '/specialties',
  path: '/specialties',
  getParentRoute: () => rootRouteImport,
} as any)
const StoriesRoute = StoriesRouteImport.update({
  id: '/stories',
  path: '/stories',
  getParentRoute: () => rootRouteImport,
} as any)
const VaccinationRoute = VaccinationRouteImport.update({
  id: '/vaccination',
  path: '/vaccination',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/diagnostics': typeof DiagnosticsRoute
  '/doctors': typeof DoctorsRoute
  '/growth-development': typeof GrowthDevelopmentRoute
  '/resources': typeof ResourcesRoute
  '/specialties': typeof SpecialtiesRoute
  '/stories': typeof StoriesRoute
  '/vaccination': typeof VaccinationRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/diagnostics': typeof DiagnosticsRoute
  '/doctors': typeof DoctorsRoute
  '/growth-development': typeof GrowthDevelopmentRoute
  '/resources': typeof ResourcesRoute
  '/specialties': typeof SpecialtiesRoute
  '/stories': typeof StoriesRoute
  '/vaccination': typeof VaccinationRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/diagnostics': typeof DiagnosticsRoute
  '/doctors': typeof DoctorsRoute
  '/growth-development': typeof GrowthDevelopmentRoute
  '/resources': typeof ResourcesRoute
  '/specialties': typeof SpecialtiesRoute
  '/stories': typeof StoriesRoute
  '/vaccination': typeof VaccinationRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/contact'
    | '/diagnostics'
    | '/doctors'
    | '/growth-development'
    | '/resources'
    | '/specialties'
    | '/stories'
    | '/vaccination'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/diagnostics'
    | '/doctors'
    | '/growth-development'
    | '/resources'
    | '/specialties'
    | '/stories'
    | '/vaccination'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/contact'
    | '/diagnostics'
    | '/doctors'
    | '/growth-development'
    | '/resources'
    | '/specialties'
    | '/stories'
    | '/vaccination'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ContactRoute: typeof ContactRoute
  DiagnosticsRoute: typeof DiagnosticsRoute
  DoctorsRoute: typeof DoctorsRoute
  GrowthDevelopmentRoute: typeof GrowthDevelopmentRoute
  ResourcesRoute: typeof ResourcesRoute
  SpecialtiesRoute: typeof SpecialtiesRoute
  StoriesRoute: typeof StoriesRoute
  VaccinationRoute: typeof VaccinationRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/diagnostics': {
      id: '/diagnostics'
      path: '/diagnostics'
      fullPath: '/diagnostics'
      preLoaderRoute: typeof DiagnosticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/doctors': {
      id: '/doctors'
      path: '/doctors'
      fullPath: '/doctors'
      preLoaderRoute: typeof DoctorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/growth-development': {
      id: '/growth-development'
      path: '/growth-development'
      fullPath: '/growth-development'
      preLoaderRoute: typeof GrowthDevelopmentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resources': {
      id: '/resources'
      path: '/resources'
      fullPath: '/resources'
      preLoaderRoute: typeof ResourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/specialties': {
      id: '/specialties'
      path: '/specialties'
      fullPath: '/specialties'
      preLoaderRoute: typeof SpecialtiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stories': {
      id: '/stories'
      path: '/stories'
      fullPath: '/stories'
      preLoaderRoute: typeof StoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vaccination': {
      id: '/vaccination'
      path: '/vaccination'
      fullPath: '/vaccination'
      preLoaderRoute: typeof VaccinationRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ContactRoute: ContactRoute,
  DiagnosticsRoute: DiagnosticsRoute,
  DoctorsRoute: DoctorsRoute,
  GrowthDevelopmentRoute: GrowthDevelopmentRoute,
  ResourcesRoute: ResourcesRoute,
  SpecialtiesRoute: SpecialtiesRoute,
  StoriesRoute: StoriesRoute,
  VaccinationRoute: VaccinationRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
